# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.IntegerField(default=0),
        ),
    ]
