# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_app', '0002_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.IntegerField(),
        ),
    ]
